version: "2.2"

services:
  client:
    image: game:client
    init: true
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - redis
    environment:
      - CHOKIDAR_USEPOLLING=true
      - SKIP_PREFLIGHT_CHECK=true
    stdin_open: true

  backend:
    image: game:server
    init: true
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
    expose:
      - 6379
